// data.js - Featured Cars with professional image URLs and complete specifications
export const featuredCars = [
  {
    id: 1,
    make: "Tesla",
    model: "Model S",
    year: 2024,
    price: 40000,
    mileage: 15000,
    transmission: "Automatic",
    fuelType: "Electric",
    color: "white",
    wishlisted: false,
    image: "https://images.unsplash.com/photo-1617788138017-80ad40651399",
  },
  {
    id: 2,
    make: "BMW",
    model: "i8",
    year: 2023,
    price: 35000,
    mileage: 22000,
    transmission: "Automatic",
    fuelType: "Hybrid",
    color: "blue",
    wishlisted: false,
    image: "/i77.jpg",
  },
  {
    id: 3,
    make: "Audi",
    model: "R8",
    year: 2022,
    price: 75000,
    mileage: 12000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Black",
    wishlisted: false,
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?q=80&w=2070&auto=format&fit=crop",
  },
{
  id :4,
  make : "Nissan",
  model : "GT-R",
  year : 2020,
  price : 260000,
  mileage : 1000,
  transmission : "Automatic",
  fuelType : "Petrol",
  color : "Grey",
  wishlisted : false,
  image : "/gtr.png",
},
{
    id: 5,
    make: "Mercedes-Benz",
    model: "C-Class",
    year: 2021,
    price: 30000,
    mileage: 25000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "blue",
    wishlisted: false,
    image: "/benzy.png",
},

{
    id: 6,
    make: "Porsche",
    model: "Taycan",
    year: 2025,
    price: 120000,
    mileage: 500,
    transmission: "Automatic",
    fuelType: "Electric",
    color: "white",
    wishlisted: false,
    image: "/taycan.jpg",
}

];

export const carMakes = [
    { id:1, name : "tesla" ,image : "/mod/teslam.jpg" },
    { id:2, name : "bmw", image : "/mod/bmwm.jpg" },
    { id:3, name : "audi", image : "/mod/audim.jpg" },
    { id:4, name : "Nissan", image : "/mod/nissanmm.jpg" },
    { id:5, name : "mercedes", image : "/mod/benzn.jpg" },
    { id:6, name : "porsche", image : "/mod/pom..png" },
];

export const bodyTypes = [
    { id:1, name : "sedan"},
    { id:2, name : "coupe"},
    { id:3, name : "convertible"},
];