export const featuredCars = [
  {
    id: 1,
    make: "Tesla",
    model: "Model S",
    year: 2022,
    price: 20000,
    mileage: 15000,
    transmission: "Automatic",
    fuelType: "Electric",
    color: "Red",
    wishlisted: false,
    image: "/tesla.jpg",
  },
  {
    id: 2,
    make: "BMW",
    model: "i8",
    year: 2021,
    price: 15000,
    mileage: 22000,
    transmission: "Automatic",
    fuelType: "Hybrid",
    color: "Blue",
    wishlisted: false,
    image: "/bmwi8.jpg",
  },
  {
    id: 3,
    make: "Audi",
    model: "R8",
    year: 2020,
    price: 58000,
    mileage: 12000,
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "White",
    wishlisted: false,
    image: "/r8.jpg",
  },
  {
    id: 4,
    make: "Mercedes",
    model: "C200",
    year: 2020,
    price: 16000,
    mileage: 30000,
    transmission: "Automatic",
    fuelType: "Diesel",
    color: "Black",
    wishlisted: false,
    image: "/c200.jpg",
  },
  {
    id: 5,
    make: "Toyota",
    model: "Vitz",
    year: 2020,
    price: 4000,
    mileage: 45000,
    transmission: "Manual",
    fuelType: "Petrol",
    color: "Silver",
    wishlisted: false,
    image: "/vitz.jpg",
  },
];

export const carMakes = [
  { id: 1, name: "Tesla", image: "/tesla.jpg" },
  { id: 2, name: "BMW", image: "/bmwi8.jpg" },
  { id: 3, name: "Audi", image: "/r8.jpg" },
  { id: 4, name: "Mercedes", image: "/c200.jpg" },
  { id: 5, name: "Toyota", image: "/vitz.jpg" },
];

export const bodyTypes = [
  { id: 1, name: "Sedan", image: "/sedan.jpg" },
  { id: 2, name: "SUV", image: "/suv.jpg" },
  { id: 3, name: "Coupe", image: "/coupe.jpg" },
  { id: 4, name: "Hatchback", image: "/hatchback.jpg" },
  { id: 5, name: "Convertible", image: "/convertible.jpg" },
];